# Generated by Django 4.2.1 on 2023-08-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GradApp', '0002_rename_is_cancelled_flight_iscancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='iscancelled',
            new_name='is_cancelled',
        ),
    ]
